micronaut:
  application:
    name: keymanagerGrpc
datasources:
  default:
    url: jdbc:mysql://localhost:3306/keymanager-grpc?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: eduardo
    password: password
    dialect: MYSQL
#    schema-generate: CREATE_DROP
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop

sistemas:
  erp:
    url: ${ERP_URL:`http://localhost:9091`}
