apiVersion: v1
kind: Service
metadata:
  name: svc-keymanager-grpc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    api: keymanager-grpc
  ports:
    - name: grpc-server
      port: 50051
      protocol: TCP
    - name: management-server
      port: 8085
      protocol: TCP
    - name: micronaut-server
      port: 8081
      protocol: TCP